[tool.black]
line-length = 100
skip-string-normalization = true
target-version = ["py36", "py37", "py38"]
exclude = '''
/(
    \.pytest_cache
    \.mypy_cache
)/
'''

[tool.interrogate]
ignore-init-method = true
ignore-init-module = false
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-module = false
fail-under = 95
exclude = []
ignore-regex = ["^get$", "^mock_.*", ".*BaseClass.*"]
verbose = 2
quiet = false
color = true
whitelist-regex = []